### ISSUE TITLE
Install broken

### ISSUE THREAD

**Issue by firefart** [x90skysn3k/brutespray#120]
```
go install github.com/x90skysn3k/brutespray@latest
go: downloading github.com/x90skysn3k/brutespray v0.0.0-20240610185117-4efb5f387cf4
go: github.com/x90skysn3k/brutespray@v0.0.0-20240610185117-4efb5f387cf4 requires go >= 1.22.4; switching to go1.22.4
go: downloading go1.22.4 (linux/amd64)
go: github.com/x90skysn3k/brutespray@latest (in github.com/x90skysn3k/brutespray@v0.0.0-20240610185117-4efb5f387cf4):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.****
```

**Comment by x90skysn3k** [comment]
This is because the `go.mod` file requires a replace on the rdp library. Alternatively run these commands to install:

`git clone https://github.com/x90skysn3k/brutespray.git`
`cd brutespray`
`go install` 

You can also just build it and move the binary wherever you'd like to install it. Another option is running it from the docker container as well.

**Comment by x90skysn3k** [comment]
I have fixed this by forking the `grdp` module and renaming it removing the replace in the `go.mod` file. Now you can use `go install github.com/x90skysn3k/brutespray@dev` until I merge this into the main branch.
